# Generated by Django 4.2.5 on 2023-09-25 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtoresDiretores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField()),
                ('site', models.CharField()),
                ('insta', models.CharField()),
                ('face', models.CharField()),
                ('twitter', models.CharField()),
                ('nacionalidade', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Continentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Episodios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField()),
                ('duracao', models.CharField()),
                ('data_disponibilizacao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField()),
                ('continente', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField()),
                ('sinopse', models.CharField()),
                ('site_oficial', models.CharField()),
                ('data_lancamento', models.DateField()),
                ('diretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.atoresdiretores')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.genero')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paises')),
            ],
        ),
        migrations.CreateModel(
            name='Temporadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='SeriesComEpisodios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.episodios')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.series')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.temporadas')),
            ],
        ),
        migrations.CreateModel(
            name='FilmeAtores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filme', models.CharField()),
                ('ator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.atoresdiretores')),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField()),
                ('sinopse', models.CharField()),
                ('site_oficial', models.CharField()),
                ('data_lancamento', models.DateField()),
                ('genero', models.CharField()),
                ('diretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.atoresdiretores')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paises')),
            ],
        ),
    ]
